FROM scratch
ADD config/image/centos-7-docker.tar.xz / 

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="CentOS Base Image" \
    org.label-schema.vendor="CentOS" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20181006"

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y update ; \
yum -y install epel-release openssh openssh-server openssh-clients wget tcping iproute sudo tree vim; \
yum clean all ; \
groupadd -r automation; useradd -r -m -g automation -s /bin/bash ansible

ADD config/ssh.tgz /root/
ADD config/ssh.tgz /home/ansible/
ADD config/sshd_config /etc/ssh/sshd_config
ADD config/sshd-banner /etc/ssh/sshd-banner
ADD config/bashrc /etc/bashrc
ADD config/DIR_COLORS /etc/DIR_COLORS_ADAM
ADD config/vimrc /root/.vimrc

RUN chown -R root:root /root/.ssh ; chown -R ansible:automation /home/ansible/.ssh ; \
sed -i "s,account    required     pam_nologin.so,#account    required     pam_nologin.so,g" /etc/pam.d/sshd ; \
sed -i "s,#   StrictHostKeyChecking ask,   StrictHostKeyChecking no,g" /etc/ssh/sshd_config ; \
sed -i "/^root/aansible ALL=(ALL) NOPASSWD: ALL" /etc/sudoers ; \
chmod 600 /home/ansible/.ssh/authorized_keys ; chmod 600 /root/.ssh/authorized_keys ; rm /etc/localtime ; ln -s /usr/share/zoneinfo/Asia/Taipei /etc/localtime 

EXPOSE 22/tcp
CMD ["/usr/sbin/init"]
